// generated by mBlock5 for mBot
// codes make you happy

#include <MeMCore.h>
#include <Arduino.h>
#include <Wire.h>
#include <SoftwareSerial.h>
#include "math.h"

/*
  Runder Schalter -> LEDs
  Kippschlater  -> Gsichtli im Display
  Ultraschall   -> Ventilator

  Hardware:
  Port1     RJ25 input
      Slot 1: runder Schalter
      Slot 2: Kippschalter
  Port2     RJ25 output
      Slot 1: LEDs
      Slot 2: -
  Port3     Display
  Port4     Fan
*/


//Port 1: slider
//MePort input(PORT_1);
MePotentiometer potentiometer(PORT_1);

//Port 3: matrix led
MeLEDMatrix ledMatrix(PORT_3);
unsigned char drawBuffer[16];
unsigned char *drawTemp;

MeBuzzer buzzer;
MeLightSensor lightsensor(6);

// Port 4 - RGB
MeRGBLed rgbled(PORT_4);


uint8_t counter = 65;

uint8_t index, red, green, blue =0;

uint8_t Bitmap_Rocket[16]=
{
 0b00011000,
 0b00011000,
 0b00011000,
 0b00100100,
 0b00100100,
 0b01000010,
 0b10000001,
 0b10000001,
 0b10000001,
 0b10000001,
 0b01000010,
 0b01000010,
 0b00100100,
 0b00100100,
 0b01000010,
 0b00000000,
};

void _delay(float seconds) {
  long endTime = millis() + seconds * 1000;
  while (millis() < endTime) _loop();
}

void setup() {

  // RJ25 adapter
  Serial.begin(9600);

  ledMatrix.setColorIndex(3);
  ledMatrix.setBrightness(3);

  //pinMode(A0, INPUT);

  //signal readyness
  //buzzer.tone(262, 0.25 * 1000);
  //delay(20);

  //fan.run(FAN_SPEED);
  //fan.stop();
  //delay(500);
    /*
    rgbled.setColor(0,0,0,0);
    rgbled.setColor(1,0,0,0);
    rgbled.setColor(2,0,0,0);
    rgbled.setColor(3,0,0,0);
    
    rgbled.show();
    */

    rgbled.reset(PORT_4);
    rgbled.show();


welcome();
}

void welcome(){


  ledMatrix.showNum(3);
  delay(1000);//ms
  
  ledMatrix.showNum(2);
  delay(1000);//ms
  
  ledMatrix.showNum(1);
  delay(1000);//ms
  
  ledMatrix.drawBitmap(0, 0, sizeof(Bitmap_Rocket), Bitmap_Rocket);
     
}

void _loop() {
}

void loop() {
  _loop();

   
    counter += 13;
    Bitmap_Rocket[15] = counter;
    ledMatrix.drawBitmap(0, 0, sizeof(Bitmap_Rocket), Bitmap_Rocket);

    index = counter & 0b11;
    red = counter | 0b10000000;
    green = counter * 77;
    rgbled.setColor(index, red, green, blue);
    rgbled.show();
 
    //ledMatrix.showNum(readSlider());
 

    delay(100);//ms
}


int readSlider(){
  int read_value =potentiometer.read();
  
  return read_value;
  //float x =float(read_value)*256/1024;
  //return int(x);  
}
